In [2]:
import numpy as np

In [9]:
#Q1
my_array = np.array([[[[1,3,4]]]])
print(my_array.ndim)
#np.arange(my_array, ndmin=5)
my_array=np.array(my_array, ndmin=5)
print(my_array.ndim)

4
5


In [12]:
#Q2
Array1 = np.array([[1, 2, 3], [4, 5, 6]])
Array2 = np.array([[2, 3],[3, 2]])
np.dot(Array1, Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [20]:
#Q3
array1 = np.array([10,3,1,203,404,204,20,302,30,402,192])
array1[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [21]:
#Q4
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [22]:
#Q5
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [23]:
#Q6
import numpy as np
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [28]:
#Q7
np.random.seed(100)
ar1 = np.random.uniform(1,50, 20)
ar1=np.clip(ar1, a_min=10, a_max=30)
print(ar1)

np.random.seed(100)
ar2 = np.random.uniform(1,50, 20)
ar2=np.where(ar2 < 10, 10, np.where(ar2 > 30, 30, ar2))
print(ar2)


[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [33]:
#Q8
array1 = np.array([10,3,1,203,404,204,20,302,30,402,192])
array2 = [1,2,3,4]
#The position to be inserted at = before 404
np.insert(array1, 4, array2)


array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [35]:
#Q9
np.full((3,3), 'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [43]:
#Q10
def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j+1] = temp
    return array
my_array = np.array([20,14,25,16,45,60,12,9])

bub_sort(my_array)


array([60, 45, 25, 20, 16, 14, 12,  9])

In [52]:
#Q11
arr=[[2,3,5,4,1],[1,2,3,4,5]]
print(np.shape(arr))
arr2=np.reshape(arr,(5,2))
print(np.shape(arr2))

(2, 5)
(5, 2)


In [54]:
#Q12
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
Sample.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
#Q13
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(Sample[0:3, 1])


[2 5 8]


In [68]:
#Q14
Array1 =np.arange(20,2)
print(Array1)
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array2)
np.hstack((Array1,Array2))

[]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
#Q15
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
np.row_stack((array1,array2))



array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
#Q16
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
np.column_stack((array1,array2))



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
#Q17
A = np.array([[4],[12],[29]])
B = np.array([[13],[21],[4]])
print(A)
print(B)
np.cross(A,B)


[[ 4]
 [12]
 [29]]
[[13]
 [21]
 [ 4]]


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [78]:
#Q18
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
R3=np.corrcoef(A,B)
R3

array([[1., 1.],
       [1., 1.]])

In [84]:
#Q19
sample = {1: [1,2],
2: [[1],[2]],
3: [[1,2], [3,4], [4,5]],
4: [1],
5: [1,2,3,4,5]}
list1=list(sample.items())
arr1=np.array(list1)
print(arr1)
type(arr1)

[[1 list([1, 2])]
 [2 list([[1], [2]])]
 [3 list([[1, 2], [3, 4], [4, 5]])]
 [4 list([1])]
 [5 list([1, 2, 3, 4, 5])]]


C:\Users\shaji\AppData\Local\Temp/ipykernel_8080/634787270.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array(list1)


numpy.ndarray

In [95]:
#Q20
arr1=np.random.randint(1,9,(3,3))
print(arr1)
print(arr1.ndim)
print('Max Value :',np.max(arr1))
print('Min Value :',np.min(arr1))

print('Diff. Between Max and Min :',np.max(arr1)-np.min(arr1))

[[7 3 5]
 [4 8 6]
 [2 1 1]]
2
Max Value : 8
Min Value : 1
Diff. Between Max and Min : 7
